version: '3.3'

services:
  app:
    container_name: "${PROJECT_NAME_UNDERSCORE}_app"
    build:
      context: ./config/docker-config
      dockerfile: Dockerfile-app
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
       - db
    volumes:
      - "./system:/var/www/${PROJECT_NAME_DASH}"

  db:
    container_name: "${PROJECT_NAME_UNDERSCORE}_db"
    build:
      context: ./config/docker-config
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - "./config:/var/config"
    environment:
       MYSQL_ROOT_PASSWORD: $PASSWORD
       MYSQL_DATABASE: "${PROJECT_NAME_UNDERSCORE}"
       MYSQL_USER: $USER
       MYSQL_PASSWORD: $PASSWORD
