version: '3.3'

services:
  app:
    container_name: "${PROJECT_NAME_UNDERSCORE}_app"
    build:
      context: ./config/docker-config
      dockerfile: Dockerfile-app
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./public:/var/www/html/"
