version: '3.3'

services:
  app:
    container_name: "<%= projectNameUnderscore %>_app"
    build:
      context: ./docker
      dockerfile: Dockerfile-app
    ports:
      - "80"
      - "443"
    restart: always
    depends_on:
      - db
    volumes:
      - ".:/var/www/<%= projectNameDash %>"

  db:
    container_name: "<%= projectNameUnderscore %>_db"
    build:
      context: ./docker
      dockerfile: Dockerfile-db
    ports:
      - "3306"
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: "<%= projectNameUnderscore %>"
       MYSQL_USER: admin
       MYSQL_PASSWORD: admin
