FROM php:7.0-apache-jessie

RUN apt-get upgrade && apt-get update

RUN apt-get install -y --no-install-recommends git
RUN apt-get install -y --no-install-recommends zip
RUN apt-get install -y --no-install-recommends zlib1g-dev
RUN apt-get install -y libbz2-dev
RUN apt-get install -y libpq-dev
RUN apt-get install -y libicu-dev
RUN apt-get install -y libpng-dev
RUN apt-get install -y g++

RUN docker-php-ext-install zip
RUN docker-php-ext-install bz2
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install pdo_mysql

RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl

RUN docker-php-ext-install gd

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

RUN sed -ri -e 's!/var/www/html!/var/www/<%= projectNameDash %>!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!/var/www/<%= projectNameDash %>!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN a2enmod rewrite

WORKDIR /var/www/<%= projectNameDash %>

CMD apachectl -D FOREGROUND
